//The Fibonacci Series is a mathematical series that starts with 0 and 1 and is generated by adding the two preceding numbers to generate the next one

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

int main() {
int i,a,b,x,n;
    scanf("%d", &n);
    a=0;
    b=1;
    for(i=0;i<n;i++)
    {
        printf("%d ", a);
        x=a+b;
        a=b;
        b=x;
    }
     
    return 0;
}
